### Analysis
This is a notebook to summarize the errors from the LLMs generated code

In [1]:
import pandas as pd

In [60]:
df = pd.read_csv("log_errors.csv")

In [61]:
# Group by 'columnx' and count occurrences
grouped = df.groupby('message').size().reset_index(name='count')
# Sort by the count in descending order
sorted_df = grouped.sort_values(by='count', ascending=False)
sorted_df['contains_indented'] = sorted_df['message'].str.contains('indented')
sorted_df['contains_must'] = sorted_df['message'].str.contains('must')
sorted_df['contains_has'] = sorted_df['message'].str.contains('has no')
sorted_df['contains_unexpected'] = sorted_df['message'].str.contains('unexpected')
sorted_df['contains_name'] = sorted_df['message'].str.contains('name')
sorted_df['contains_syntax'] = sorted_df['message'].str.contains('syntax')
sorted_df['contains_defined'] = sorted_df['message'].str.contains('defined')

In [ ]:
sorted_df[sorted_df['contains_name']==True].sum()

In [80]:
sorted_df[sorted_df['contains_name']==True]

,message,count,contains_indented,contains_must,contains_has,contains_unexpected,contains_name,contains_syntax,contains_defined,counts_indented,counts_must,counts_has,counts_unexpected,counts_name,counts_syntax,counts_defined
154,name 'plt' is not defined,80,False,False,False,False,True,False,True,0,0,0,0,80,0,80
152,name 'player_' is not defined,19,False,False,False,False,True,False,True,0,0,0,0,19,0,19
145,name 'df' is not defined,9,False,False,False,False,True,False,True,0,0,0,0,9,0,9
143,name 'data' is not defined,9,False,False,False,False,True,False,True,0,0,0,0,9,0,9
140,name 'Python' is not defined,7,False,False,False,False,True,False,True,0,0,0,0,7,0,7
151,name 'np' is not defined,4,False,False,False,False,True,False,True,0,0,0,0,4,0,4
157,name 'random' is not defined,3,False,False,False,False,True,False,True,0,0,0,0,3,0,3
156,name 'python' is not defined,3,False,False,False,False,True,False,True,0,0,0,0,3,0,3
158,name 'raw_' is not defined,2,False,False,False,False,True,False,True,0,0,0,0,2,0,2
155,name 'py' is not defined,2,False,False,False,False,True,False,True,0,0,0,0,2,0,2
33,No module named 'cartopy',2,False,False,False,False,True,False,False,0,0,0,0,2,0,0
144,name 'data_dict' is not defined,2,False,False,False,False,True,False,True,0,0,0,0,2,0,2
150,name 'nba_' is not defined,1,False,False,False,False,True,False,True,0,0,0,0,1,0,1
141,name 'bar_width' is not defined,1,False,False,False,False,True,False,True,0,0,0,0,1,0,1
142,name 'boroughs' is not defined,1,False,False,False,False,True,False,True,0,0,0,0,1,0,1
146,name 'dict_' is not defined,1,False,False,False,False,True,False,True,0,0,0,0,1,0,1
147,name 'family_' is not defined,1,False,False,False,False,True,False,True,0,0,0,0,1,0,1
148,name 'labels' is not defined,1,False,False,False,False,True,False,True,0,0,0,0,1,0,1
149,name 'mpl' is not defined,1,False,False,False,False,True,False,True,0,0,0,0,1,0,1
153,name 'players' is not defined,1,False,False,False,False,True,False,True,0,0,0,0,1,0,1
159,name 'weights' is not defined,1,False,False,False,False,True,False,True,0,0,0,0,1,0,1

In [62]:
sorted_df.to_csv('errors_keywords.csv', index=False)

In [74]:
sorted_df['counts_indented'] = sorted_df['contains_indented']*sorted_df['count']
sorted_df['counts_must'] = sorted_df['contains_must']*sorted_df['count']
sorted_df['counts_has'] = sorted_df['contains_has']*sorted_df['count']
sorted_df['counts_unexpected'] = sorted_df['contains_unexpected']*sorted_df['count']
sorted_df['counts_name'] = sorted_df['contains_name']*sorted_df['count']
sorted_df['counts_syntax'] = sorted_df['contains_syntax']*sorted_df['count']
sorted_df['counts_defined'] = sorted_df['contains_defined']*sorted_df['count']

In [ ]:
counts_indented                                                      254
counts_must                                                           15
counts_has                                                            16
counts_unexpected                                                      2
counts_name                                                          151
counts_syntax                                                         44
counts_defined                                                       149

In [82]:
547-100
133

414

In [83]:
133*100/547

24.314442413162705

In [81]:
254+15+16+2+151+44

482

In [75]:
sorted_df.sum()

message                Successname 'plt' is not definedexpected an in...
count                                                               1814
contains_indented                                                     57
contains_must                                                         14
contains_has                                                          16
contains_unexpected                                                    2
contains_name                                                         21
contains_syntax                                                       28
contains_defined                                                      20
counts_indented                                                      254
counts_must                                                           15
counts_has                                                            16
counts_unexpected                                                      2
counts_name                                                          151
counts_syntax                                                         44
counts_defined                                                       149
dtype: object

In [70]:
len(sorted_df[sorted_df['contains_defined'] == True])

20

In [69]:
len(sorted_df[sorted_df['contains_syntax'] == True])

28

In [71]:
len(sorted_df[sorted_df['contains_indented'] == True])

57

In [15]:
sorted_df[sorted_df['message'] not in ].head(10)

                                               message  count
34                                             Success   1267
154                          name 'plt' is not defined     80
54   expected an indented block after 'for' stateme...     27
53   expected an indented block after 'for' stateme...     27
152                      name 'player_' is not defined     19
52   expected an indented block after 'for' stateme...     15
56   expected an indented block after 'for' stateme...     13
55   expected an indented block after 'for' stateme...     13
61   expected an indented block after 'for' stateme...     11
58   expected an indented block after 'for' stateme...     11

In [44]:
for p in df[df['message'].str.contains('cartopy')]['old']:
    print(p)

Data/documents/anthropic/Airbnb_selected_top_0.8/document32
Data/documents/anthropic/Airbnb_selected_temp_0.9/document32

In [16]:
sorted_df[~sorted_df['message'].str.contains('for')].head(10)

                                               message  count
34                                             Success   1267
154                          name 'plt' is not defined     80
152                      name 'player_' is not defined     19
39       agg function failed [how->mean,dtype->object]     10
145                           name 'df' is not defined      9
143                         name 'data' is not defined      9
140                       name 'Python' is not defined      7
113                 invalid syntax (<string>, line 15)      6
173  unterminated string literal (detected at line ...      4
41   can't multiply sequence by non-int of type 'nu...      4

In [ ]:
# agg function failed [how->mean,dtype->object]

In [21]:
sorted_df[(~sorted_df['message'].str.contains('for')) & (sorted_df['count']<7)]

                                               message  count
113                 invalid syntax (<string>, line 15)      6
173  unterminated string literal (detected at line ...      4
41   can't multiply sequence by non-int of type 'nu...      4
102  expected an indented block after function defi...      4
151                           name 'np' is not defined      4
..                                                 ...    ...
45       could not convert string to float: 'Cleanser'      1
44       could not convert string to float: 'Brooklyn'      1
43   closing parenthesis '}' does not match opening...      1
42   closing parenthesis ']' does not match opening...      1
183                      x and y must be the same size      1

[118 rows x 2 columns]

In [23]:
sorted_df[(~sorted_df['message'].str.contains('for')) & (sorted_df['count']<7) & (sorted_df['count']>1)]

                                               message  count
113                 invalid syntax (<string>, line 15)      6
173  unterminated string literal (detected at line ...      4
41   can't multiply sequence by non-int of type 'nu...      4
102  expected an indented block after function defi...      4
151                           name 'np' is not defined      4
119                 invalid syntax (<string>, line 23)      3
157                       name 'random' is not defined      3
156                       name 'python' is not defined      3
112                 invalid syntax (<string>, line 14)      2
111                 invalid syntax (<string>, line 13)      2
121                 invalid syntax (<string>, line 25)      2
123                 invalid syntax (<string>, line 29)      2
1    ':' expected after dictionary key (<string>, l...      2
124                 invalid syntax (<string>, line 30)      2
130                 invalid syntax (<string>, line 64)      2
100  expected an indented block after function defi...      2
128                 invalid syntax (<string>, line 58)      2
117                 invalid syntax (<string>, line 21)      2
167                   unhashable type: 'numpy.ndarray'      2
170  unterminated string literal (detected at line ...      2
160                            no numeric data to plot      2
11   'c' argument must be a color, a sequence of co...      2
158                         name 'raw_' is not defined      2
155                           name 'py' is not defined      2
33                           No module named 'cartopy'      2
144                    name 'data_dict' is not defined      2

In [24]:
df_list = sorted_df[(~sorted_df['message'].str.contains('for')) & (sorted_df['count']<7)]
df_list.to_csv('errors_analysis.csv', index=False)

In [22]:
sorted_df[~sorted_df['message'].str.contains('is not defined')].head(10)

                           message  count
154      name 'plt' is not defined     80
152  name 'player_' is not defined     19
145       name 'df' is not defined      9
143     name 'data' is not defined      9
140   name 'Python' is not defined      7
151       name 'np' is not defined      4
157   name 'random' is not defined      3
156   name 'python' is not defined      3
158     name 'raw_' is not defined      2
155       name 'py' is not defined      2

In [40]:
analysis_df2 = sorted_df[(~sorted_df['message'].str.contains('name'))&(~sorted_df['message'].str.contains('for')) & (sorted_df['count']<7) & (sorted_df['count']>1)]

In [41]:
analysis_df2

                                               message  count
113                 invalid syntax (<string>, line 15)      6
173  unterminated string literal (detected at line ...      4
41   can't multiply sequence by non-int of type 'nu...      4
102  expected an indented block after function defi...      4
119                 invalid syntax (<string>, line 23)      3
112                 invalid syntax (<string>, line 14)      2
111                 invalid syntax (<string>, line 13)      2
121                 invalid syntax (<string>, line 25)      2
123                 invalid syntax (<string>, line 29)      2
1    ':' expected after dictionary key (<string>, l...      2
124                 invalid syntax (<string>, line 30)      2
130                 invalid syntax (<string>, line 64)      2
100  expected an indented block after function defi...      2
128                 invalid syntax (<string>, line 58)      2
117                 invalid syntax (<string>, line 21)      2
167                   unhashable type: 'numpy.ndarray'      2
170  unterminated string literal (detected at line ...      2
160                            no numeric data to plot      2
11   'c' argument must be a color, a sequence of co...      2

In [35]:
analysis_df2.to_csv("error_analysis2.csv", index=False)